name: Feature request
description: Propose an improvement or new capability for SafeAI.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please focus on the user problem, proposed behavior, and tradeoffs.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-line statement of the requested capability.
      placeholder: Add policy simulation mode for action boundary decisions.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What pain exists today and why current behavior is insufficient.
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
      description: Describe the desired behavior/API/UX with concrete details.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches and why they are weaker.
  - type: textarea
    id: scope_boundary
    attributes:
      label: Scope boundary
      description: What should explicitly remain out of scope.
      placeholder: Do not add dashboard work for this request; CLI and SDK only.
  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: Who is affected, severity, frequency, and measurable outcome.
      placeholder: |
        Affected users:
        Severity:
        Frequency:
        Expected outcome:
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Evidence or references
      description: Prior art, links, logs, metrics, or design references.

