# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 SafeAI Contributors
"""CLI commands for setting up SafeAI hooks in coding agents."""

from __future__ import annotations

import os
from pathlib import Path

import click


@click.group("setup")
def setup_group() -> None:
    """Set up SafeAI hooks for a coding agent."""


@setup_group.command("claude-code")
@click.option("--config", default="safeai.yaml", help="Path to safeai.yaml config file.")
@click.option("--path", default=".", help="Project directory to install hooks into.")
def setup_claude_code(config: str, path: str) -> None:
    """Install SafeAI hooks for Claude Code."""
    from safeai.agents.installers.claude_code import install

    install(config_path=config, project_path=path)


@setup_group.command("cursor")
@click.option("--config", default="safeai.yaml", help="Path to safeai.yaml config file.")
@click.option("--path", default=".", help="Project directory to install hooks into.")
def setup_cursor(config: str, path: str) -> None:
    """Install SafeAI hooks for Cursor."""
    from safeai.agents.installers.cursor import install

    install(config_path=config, project_path=path)


@setup_group.command("generic")
@click.option("--config", default="safeai.yaml", help="Path to safeai.yaml config file.")
def setup_generic(config: str) -> None:
    """Print instructions for manual SafeAI hook integration."""
    from safeai.agents.installers.generic import install

    install(config_path=config)


def _write_integration_file(filename: str, content: str, force: bool) -> None:
    """Write a generated integration file, warning if it already exists."""
    target = Path(os.getcwd()) / filename
    if target.exists() and not force:
        click.echo(f"⚠️  {filename} already exists. Use --force to overwrite.")
        return
    target.write_text(content)
    click.echo(f"✅ Created {filename}")


@setup_group.command("langchain")
@click.option("--force", is_flag=True, default=False, help="Overwrite existing file.")
def setup_langchain(force: bool) -> None:
    """Generate SafeAI + LangChain integration boilerplate."""
    content = '''\
"""SafeAI + LangChain integration. Generated by 'safeai setup langchain'."""
from safeai import SafeAI
from safeai.middleware.langchain import SafeAICallbackHandler

ai = SafeAI.from_config("safeai.yaml")
handler = ai.advanced.langchain_callback_handler()

# Add to your LangChain chain:
# chain.invoke({"input": "..."}, config={"callbacks": [handler]})
'''
    _write_integration_file("safeai_langchain.py", content, force)
    click.echo("Next: import handler from safeai_langchain and pass it to your chain callbacks.")


@setup_group.command("crewai")
@click.option("--force", is_flag=True, default=False, help="Overwrite existing file.")
def setup_crewai(force: bool) -> None:
    """Generate SafeAI + CrewAI integration boilerplate."""
    content = '''\
"""SafeAI + CrewAI integration. Generated by 'safeai setup crewai'."""
from safeai import SafeAI
ai = SafeAI.from_config("safeai.yaml")
hook = ai.advanced.crewai_tool_hook()
# Wrap your CrewAI tools with: hook(tool)
'''
    _write_integration_file("safeai_crewai.py", content, force)
    click.echo("Next: import hook from safeai_crewai and wrap your CrewAI tools.")


@setup_group.command("autogen")
@click.option("--force", is_flag=True, default=False, help="Overwrite existing file.")
def setup_autogen(force: bool) -> None:
    """Generate SafeAI + AutoGen integration boilerplate."""
    content = '''\
"""SafeAI + AutoGen integration. Generated by 'safeai setup autogen'."""
from safeai import SafeAI
ai = SafeAI.from_config("safeai.yaml")
hook = ai.advanced.autogen_tool_hook()
# Register with AutoGen agent's tool executor
'''
    _write_integration_file("safeai_autogen.py", content, force)
    click.echo("Next: import hook from safeai_autogen and register with your AutoGen agent.")
